### ISSUE TITLE
일부 파일들의 유니코드 문자 깨짐 문제

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#18]
일부 파일 내의 유니코드 문자들이 깨지는 현상이 있습니다.

예를 들어서 다음과 같은 부분입니다.
https://github.com/OpenRPGs/OpenRPG/blob/6496040229cc604b596c373ceb6d2043d3d0e835/OpenRPG/GameState.cpp#L59

이는 파일 인코딩을 유니코드 계열이 아닌 `CP-949(EUC-KR)`로 저장했기 때문입니다.

가능한 소스 및 헤더 파일 전체를 `UTF-8`과 같은 유니코드 계열 인코딩으로 저장하는 것을 추천드립니다.

**Comment by kiseop91** [comment]
안녕하세요!
우선 알려주셔서감사합니다. ㅎ 
저도 그 문제를 인식하고 엊그제 .editorconfig 파일을 넣어서 utf-8로 인코딩하도록 설정해두었는데 아직 깨진곳이 있는줄 몰랐네요.  확인해보겠습니다. 감사합니다.

**Comment by kiseop91** [comment]
EditorState.h 깨져있던 주석 수정했습니다. 감사합니다.

**Comment by WolfgangKurz** [comment]
`master` 브랜치 기준으로 본거라 이슈 올리고나서 혹시나 했는데 남아있었군요.

이슈 닫습니다.
