### ISSUE TITLE
소스코드 가독성 문제 및 절약

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#21]
### 요약
많은 클래스 헤더 파일에 컴파일 시에는 문제가 없겠지만, 가독성이 크게 저하되는 문제가 있습니다.

### 문제
[Document 디렉토리 내에 있는 다이어그램](https://github.com/OpenRPGs/OpenRPG/blob/b5e8a25bcc891510be52cb67387750c70a1ac2ce/Document/ClassDiagram.png)에서 클래스별 상속 구조를 볼 수 있었습니다.

하지만 대다수의 헤더가 이 다이어그램을 잘못 구현하고 있습니다.

### 예시
예를 들어, `State` 클래스는 상속하는 클래스가 없고, `MainMenuState` 및 `EditorState`에 상속됩니다.

https://github.com/OpenRPGs/OpenRPG/blob/22f1fed159382ff0c3eb364294c3702a5940dd5f/OpenRPG/State.h#L1-L6
하지만 `State.h` 파일에서는 전혀 관련 없는 `Player.h` 파일을 불러오고 있습니다.

https://github.com/OpenRPGs/OpenRPG/blob/22f1fed159382ff0c3eb364294c3702a5940dd5f/OpenRPG/State.cpp#L1-L4
그리고 해당 헤더 파일을 불러오는 `State.cpp` 파일에서는 `State.h` 파일만을 `include`하고 있을 뿐입니다.

### 수정 방안 및 설명
모든 헤더 클래스 헤더 파일은 클래스를 정의하는 데에만 사용되어야 합니다.

해당 클래스 내부 멤버 또는 메서드에 사용되는 타입이 있더라도, 그 타입이 정의된 헤더 파일은 `include` 하지 않는 것이 좋습니다.

필요한 정의는 모두 `cpp` 파일에서 `include` 되어야 가독성이 지켜질 수 있습니다.

다이어그램을 구성했다면, 다이어그램에 충실해야 합니다.

(헤더 파일에서 모든 `include` 문을 없애라는 것이 아니라, 관련 없는 `include`를 지양하는 것이 바람직하다는 의견입니다.)

### 추가 내용
추가로, 소스코드를 절약하고 가독성을 보완하는 방안이 있습니다.

현재 클래스 헤더 파일에는 다음과 같은 구성이 사용되고 있습니다.

```c++
#ifndef IDENTIFIER
#define IDENTIFIER

// ~~~

#endif
```
이와 같은 방식은 단언컨대, **낡은 구현을 사용한 소스코드**입니다.

`Include guard`라고 불리는 이것은 꽤 오래전부터 다음 한 줄로 대체되었습니다.

```c++
#pragma once
```
위 `pragma` 구문을 사용한 것이 **더 안전하고 간편**합니다.

**Comment by kiseop91** [comment]
오 이렇게 리뷰해주시니 너무감사하네용
ToDo리스트에 추가하고 변경하겠습니다

**Comment by kiseop91** [comment]
develop브랜치에 수정완료했습니다.

**Comment by kiseop91** [comment]
처리완료되었습니다. 이슈닫습니다.
