### ISSUE TITLE
키 및 마우스 입력 포커스 문제

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#22]
### 문제
비 포커스 상태에서도 키 입력 및 마우스 입력이 발생함.

### 수정 방안
입력 처리 이전에 포커스 여부를 검사하여 포커스 상태가 아니라면 처리하지 않도록 수정.

https://github.com/OpenRPGs/OpenRPG/blob/b5e8a25bcc891510be52cb67387750c70a1ac2ce/OpenRPG/GameState.cpp#L105-L119
아마도 이 부분...

**Comment by kiseop91** [comment]
확인결과 화면밖에서 의도치않은 입력이 들어가는 것을 확인했습니다. 감사합니다 ㅎ

**Comment by kiseop91** [comment]
develop브랜치에 해당 오류를 수정한 커밋을 올렸습니다.
