### ISSUE TITLE
BGM 처리 문제

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#24]
### 문제 및 원인
타이틀 화면에서 에디터로 진입 후 `Escape` 키를 통해 다시 타이틀로 돌아오면 타이틀 BGM이 재생되지 않습니다.

현재 소스코드로는 `initMusic`에서 BGM을 재생하고, 화면 이동시에 `this->bgm->stop()`을 호출하여 BGM을 중지하고 있습니다.

`initMusic`은 객체 생성시에 한 번만 호출되므로, `state`가 `pop`되어 화면을 변경하는 경우에는 BGM이 재생되지 않습니다.

### 수정 방안
`init` 시점이 아닌, `state`가 변경되어 타이틀이 될 때에 BGM을 재생하는 작업이 이루어지면 될 것으로 보입니다.

`SoundManager` 클래스를 만들어서 관리해주면 수월하리라 생각됩니다.

**Comment by kiseop91** [comment]
확인하였습니다. 감사합니다 😄

**Comment by kiseop91** [comment]
처리완료 이슈닫습니다.
