### ISSUE TITLE
프로그램 진입점 문제

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#25]
### 문제 및 원인
진입점이 `main` 으로 되어있어 프로그램 실행 시 콘솔이 표시되고 이후에 게임 창이 표시됩니다.

개발 단계에서는 문제가 없겠지만 이후 배포 단계를 생각하면 수정해야 할 문제입니다.

만약 게임의 컨셉이 콘솔을 같이 이용하는 것이라면, 아무런 문제가 없겠지만 말이죠.

### 수정 방안
진입점을 `WinMain`으로 변경하여 프로그램 시작 시 콘솔이 표시되지 않도록 합니다.

디버깅 등의 목적으로 콘솔 출력이 필요하다면 별도로 콘솔을 생성하여 사용하도록 합니다.

```c++
// 새 콘솔을 생성
AllocConsole();

// 출력 및 입력 스트림을 재설정
freopen("CONIN$", "rb", stdin);
freopen("CONOUT$", "wb", stdout);
freopen("CONOUT$", "wb", stderr);

// cout, cin, cerr를 사용한다면 다음 줄의 주석을 제거
// std::ios::sync_with_stdio();

// 필요하다면 콘솔의 제목을 변경
// SetConsoleTitle(...);

...

// 사용 후 반드시 해제
FreeConsole();
```

혹은 `main` 진입과 동시에 콘솔 창을 숨기는 방법도 있습니다.

```c++
// 현재 콘솔의 핸들을 가져옴
HWND hWndConsole = GetConsoleWindow();
if(hWndConsole)
    ShowWindow(hWndConsole, SW_HIDE); // 숨기기
```

**Comment by kiseop91** [comment]
감사합니다.
