### ISSUE TITLE
Manager들이 할당된 메모리를 제대로 해제하지않음

### ISSUE THREAD

**Issue by kiseop91** [OpenRPGs/OpenRPG#32]
싱글턴으로 구현된 메니저들이 메모리를 반납하지않는 문제 발견.
![image](https://user-images.githubusercontent.com/15700118/63429831-29db9a00-c456-11e9-93bc-46a3ad2e82d1.png)

**Comment by WolfgangKurz** [comment]
### 원인
`sf::Texture` 및 `sf::SoundBuffer` 등 불러온 후 해제가 이루어져야 하는 자원들의 사용을 **참조**로 사용하고 있어 정확한 해제 시점을 알 수 없음.

심지어 `State`마저도 언제 해제될지 알 수 없음.

따라서 `State`가 해제되지 않아 `State`가 가지고 있는 자원들도 해제되지 않으면서 누수가 발생하는 것으로 확인됨.

### 해결 방안
`State`의 사용이 끝나면 확실히 `delete` 해주거나 스마트 포인터를 이용하여 아무튼 더 이상 참조되지 않을 때 해제하도록 조치.

모든 `sf::Texture`, `sf::SoundBuffer` 등의 자원을 참조가 아닌 포인터로 전달하고 사용하고, `delete`를 통해 확실히 소멸할 수 있도록 처리.

### 진행
현재 수정중

**Comment by kiseop91** [comment]
제가 기존에 생각했던방식은 해당스테이트에서 할당을 받으면 그 스테이트에서 반납하는 것을 원칙으로 했는데 싱글턴으로 바뀌면서 이게 애매해졌네요.

**Comment by kiseop91** [comment]
매니저 자원해제 메서드들에 (clear 나 cleanup 또는 소멸자) 출력넣고 찍어보니 전부 호출이 안되더라고요

**Comment by WolfgangKurz** [comment]
구조적으로나 장기적으로나 포인터를 통해 관리하는게 안전하긴 합니다.

관리가 힘들면 스마트 포인터를 써도 좋구요.

**Comment by kiseop91** [comment]
일단 ToDO리스트에 스마트포인터작업추가했습니다. 하나씩 처리해봐야겠네요 감사합니다.

**Comment by kiseop91** [comment]
찾았습니다. SoundManger의 소멸자가 호출되지않기때문에   soundComponent의 sound가 해제되지않아 생긴문제였네요. sound해제해주니 사라졌습니다.

**Comment by WolfgangKurz** [comment]
그 부분도 포함해서 수정중이긴 합니다. 오늘 저녁이나 내일즈음에 풀리퀘스트 들어갈 것 같네요.

**Comment by kiseop91** [comment]
원인 :  State를 관리하는 StateManager에서 State에 할당된 자원을 해제하지않음. State의 sounds컨테이너에 들어있는 SoundBuffer의 소멸자가 호출되지않아생기는 문제.
같은 이유로 SoundManager가 관리하는 SoundComponent의 sound객체의 메모리를 해제하지않음.

해결 : 싱글턴으로 구현된 각 메니저가 소멸자를 호출하지않아 생기는 문제로, destroy정적함수를 따로만들어 싱글턴인스턴스가 생성될 때 , atexit함수에 등록하여 main함수가 끝나기직전에 호출해 각 메니저의 소멸자를 호출하도록 구현하여 해결하였음.
