### ISSUE TITLE
🎵 오디오 파일 코덱 문제

### ISSUE THREAD

**Issue by WolfgangKurz** [OpenRPGs/OpenRPG#37]
### 개요
현재 오디오 파일은 `MainMenuState`에서만 사용중입니다.

`PCM WAVE`를 사용중이고, 때문에 약 `41MB` 용량을 가지고 있고, 오디오를 불러올 때 상당한 시간이 걸리게 됩니다.

용량 절약 및 불러오기 시간을 해결하기 위해 특정 코덱으로 압축하고 디코딩하는 과정을 가져야 합니다.

### 라이브러리 후보
1. [libvorbis & libogg](https://xiph.org/) (Ogg Vorbis, BSD)
2. [OpenMP3](https://github.com/audioboy77/OpenMP3/) (mp3, Unlicense)

위 두 코덱으로 충분하다고 생각되어 이외의 코덱은 살펴보지 않았습니다.

더 괜찮은 후보가 있다면 추가될 수 있습니다.

### 설명
1. libvorbis & libogg
    ogg 확장자의 파일에 주로 담기는 코덱을 디코딩합니다.
    샘플링 레이트는 `8kHz ~ 192kHz`의 범위를 가집니다.
    비트레이트는 최대 `500kbps`까지 가능합니다.
    `mp3` 파일보다 디코딩 속도가 많이 느립니다.
2. OpenMP3
    mp3 확장자 파일을 디코딩합니다.
    샘플링 레이트는 `22kHz ~ 48kHz`의 범위를 가집니다.
    비트레이트는 최대 `320kbps`까지 가능합니다.
    같은 음원 대비 `Vorbis`보다 디코딩 속도가 빠릅니다.

### 개인적인 견해
인코딩 후의 용량 차이가 거의 없고, 음질이 매우 중요한 프로젝트가 아닙니다.

라이브러리 자체가 가볍기도 하고, 라이센스적으로도 매우 자유로운 `OpenMP3`를 사용하는게 어떨까 싶습니다.

**Comment by kiseop91** [comment]
확인했습니다.  라이센스가 없는 OpenMP3도 있군요. 앞으로는 사운드리소스는 OpenMP3로 사용하겠습니다. 감사합니다!

**Comment by WolfgangKurz** [comment]
지금 확인해보니 `SFML` 자체적으로 `OGG` 및 `FLAC`을 지원하고 있네요.

BGM과 같은 큰 파일은 `sf::Music` 클래스가 알아서 스트리밍 방식으로 구현되어 있습니다.

라이브러리 연동이 필요 없다는 점에서 기존 `SFML`의 코드를 사용해도 무방해보입니다.

이슈는 클로즈 하도록 하겠습니다.
